# Generated by Django 5.0.3 on 2024-03-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('partya', models.IntegerField(max_length=20)),
                ('partyb', models.IntegerField(max_length=20)),
                ('call_duration', models.IntegerField(max_length=20)),
                ('usage_type', models.CharField(max_length=20)),
                ('cell_type', models.CharField(max_length=20)),
                ('lac_id', models.IntegerField(max_length=20)),
                ('cell_id', models.IntegerField(max_length=20)),
                ('imei', models.IntegerField(max_length=20)),
                ('imsi', models.IntegerField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('partyb_original', models.IntegerField(max_length=20)),
            ],
        ),
    ]
