# Generated by Django 5.0.3 on 2024-03-25 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdr',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cdr',
            name='call_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='cell_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='imei',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='imsi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='lac_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='partya',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='partyb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='partyb_original',
            field=models.IntegerField(),
        ),
    ]
