# Generated by Django 5.0.3 on 2024-03-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cdr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
